[build]
builder = "nixpacks"
buildCommand = "cd server && npm install --production"

[deploy]
startCommand = "cd server && npm start"
restartPolicyType = "ON_FAILURE"

[build.environment]
NODE_ENV = "production"